<?php
/**
 * Job Board Demo Pack — 20 job listings across 5 industries.
 *
 * @package WBListora\Demo
 */

defined( 'ABSPATH' ) || exit;

require_once __DIR__ . '/class-demo-seeder.php';

use WBListora\Demo\Demo_Seeder;

// ── Categories ──

Demo_Seeder::ensure_categories(
	array(
		'engineering' => 'Engineering',
		'design'      => 'Design',
		'marketing'   => 'Marketing',
		'sales'       => 'Sales',
		'operations'  => 'Operations',
	)
);

Demo_Seeder::ensure_features(
	array(
		'remote'         => 'Remote',
		'hybrid'         => 'Hybrid',
		'onsite'         => 'On-site',
		'health-ins'     => 'Health Insurance',
		'401k'           => '401(k)',
		'equity'         => 'Equity',
		'pto'            => 'Unlimited PTO',
		'learning'       => 'Learning Budget',
		'parental-leave' => 'Parental Leave',
		'gym'            => 'Gym Membership',
	)
);

// ── Listings ──

$listings = array(
	// ── Engineering ──
	array(
		'title'      => 'Senior Full-Stack Engineer',
		'type'       => 'job',
		'categories' => array( 'Engineering' ),
		'featured'   => true,
		'features'   => array( 'remote', 'health-ins', '401k', 'equity', 'pto' ),
		'tags'       => array( 'react', 'node.js', 'typescript', 'aws' ),
		'content'    => 'We are looking for a Senior Full-Stack Engineer to join our growing team and help build the next generation of our SaaS platform. You will work across the entire stack, from designing React-based UIs to building scalable Node.js microservices. We value clean code, thoughtful architecture, and a passion for user experience. This is a fully remote position with flexible hours.',
		'meta'       => array(
			'address'          => array(
				'address'     => '350 5th Avenue, Midtown, NY 10118',
				'lat'         => 40.7484,
				'lng'         => -73.9857,
				'city'        => 'New York',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '10118',
			),
			'company'          => 'TechFlow Inc.',
			'salary_min'       => 150000,
			'salary_max'       => 200000,
			'salary_type'      => 'annual',
			'experience_level' => 'senior',
			'remote_option'    => 'remote',
			'employment_type'  => 'full-time',
			'skills'           => array( 'React', 'Node.js', 'TypeScript', 'AWS', 'PostgreSQL' ),
			'apply_url'        => 'https://techflow.com/careers/senior-fullstack',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+30 days' ) ),
		),
	),
	array(
		'title'      => 'DevOps Engineer',
		'type'       => 'job',
		'categories' => array( 'Engineering' ),
		'features'   => array( 'hybrid', 'health-ins', '401k', 'equity' ),
		'tags'       => array( 'kubernetes', 'terraform', 'ci/cd', 'docker' ),
		'content'    => 'Join our infrastructure team to build and maintain cloud-native systems at scale. You will design CI/CD pipelines, manage Kubernetes clusters, and ensure 99.99% uptime for our platform serving millions of users. Experience with infrastructure-as-code and monitoring tools is essential.',
		'meta'       => array(
			'address'          => array(
				'address'     => '200 Park Avenue, Midtown, NY 10166',
				'lat'         => 40.7547,
				'lng'         => -73.9768,
				'city'        => 'New York',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '10166',
			),
			'company'          => 'CloudScale Systems',
			'salary_min'       => 140000,
			'salary_max'       => 185000,
			'salary_type'      => 'annual',
			'experience_level' => 'mid',
			'remote_option'    => 'hybrid',
			'employment_type'  => 'full-time',
			'skills'           => array( 'Kubernetes', 'Terraform', 'Docker', 'AWS', 'CI/CD' ),
			'apply_url'        => 'https://cloudscale.io/careers/devops',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+45 days' ) ),
		),
	),
	array(
		'title'      => 'Junior Frontend Developer',
		'type'       => 'job',
		'categories' => array( 'Engineering' ),
		'features'   => array( 'onsite', 'health-ins', 'learning', 'gym' ),
		'tags'       => array( 'javascript', 'react', 'css', 'entry level' ),
		'content'    => 'Great opportunity for a passionate developer starting their career. You will work alongside senior engineers to build beautiful, responsive web applications. We invest heavily in mentorship and professional development. You will ship real features from day one and grow rapidly in a supportive environment.',
		'meta'       => array(
			'address'          => array(
				'address'     => '85 Broad Street, Financial District, NY 10004',
				'lat'         => 40.7040,
				'lng'         => -74.0120,
				'city'        => 'New York',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '10004',
			),
			'company'          => 'Pixel Labs',
			'salary_min'       => 75000,
			'salary_max'       => 95000,
			'salary_type'      => 'annual',
			'experience_level' => 'entry',
			'remote_option'    => 'onsite',
			'employment_type'  => 'full-time',
			'skills'           => array( 'JavaScript', 'React', 'CSS', 'HTML', 'Git' ),
			'apply_url'        => 'https://pixellabs.co/careers/junior-frontend',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+21 days' ) ),
		),
	),
	array(
		'title'      => 'Mobile Engineer (iOS)',
		'type'       => 'job',
		'categories' => array( 'Engineering' ),
		'featured'   => true,
		'features'   => array( 'remote', 'health-ins', '401k', 'equity', 'pto' ),
		'tags'       => array( 'swift', 'ios', 'swiftui', 'mobile' ),
		'content'    => 'Build delightful iOS experiences used by millions. We are looking for a talented iOS engineer who cares deeply about craft, performance, and user experience. You will own features end-to-end, from design collaboration through App Store release. SwiftUI experience strongly preferred.',
		'meta'       => array(
			'address'          => array(
				'address'     => '1 World Trade Center, NY 10007',
				'lat'         => 40.7127,
				'lng'         => -74.0134,
				'city'        => 'New York',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '10007',
			),
			'company'          => 'AppForge',
			'salary_min'       => 130000,
			'salary_max'       => 175000,
			'salary_type'      => 'annual',
			'experience_level' => 'mid',
			'remote_option'    => 'remote',
			'employment_type'  => 'full-time',
			'skills'           => array( 'Swift', 'SwiftUI', 'iOS', 'Xcode', 'Core Data' ),
			'apply_url'        => 'https://appforge.dev/careers/ios',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+35 days' ) ),
		),
	),
	// ── Design ──
	array(
		'title'      => 'Senior Product Designer',
		'type'       => 'job',
		'categories' => array( 'Design' ),
		'featured'   => true,
		'features'   => array( 'remote', 'health-ins', 'equity', 'pto', 'learning' ),
		'tags'       => array( 'figma', 'ux', 'ui', 'design systems' ),
		'content'    => 'Shape the future of how teams collaborate. As a Senior Product Designer, you will lead design for key product areas, conduct user research, create prototypes, and work closely with engineering to ship polished experiences. You will also contribute to our design system and mentor junior designers.',
		'meta'       => array(
			'address'          => array(
				'address'     => '110 Greene Street, SoHo, NY 10012',
				'lat'         => 40.7245,
				'lng'         => -73.9998,
				'city'        => 'New York',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '10012',
			),
			'company'          => 'CollabSpace',
			'salary_min'       => 140000,
			'salary_max'       => 180000,
			'salary_type'      => 'annual',
			'experience_level' => 'senior',
			'remote_option'    => 'remote',
			'employment_type'  => 'full-time',
			'skills'           => array( 'Figma', 'User Research', 'Prototyping', 'Design Systems', 'Interaction Design' ),
			'apply_url'        => 'https://collabspace.com/careers/product-designer',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+28 days' ) ),
		),
	),
	array(
		'title'      => 'UX Researcher',
		'type'       => 'job',
		'categories' => array( 'Design' ),
		'features'   => array( 'hybrid', 'health-ins', '401k', 'learning' ),
		'tags'       => array( 'user research', 'usability testing', 'surveys', 'analytics' ),
		'content'    => 'Drive product decisions with data and empathy. You will plan and conduct qualitative and quantitative research studies, synthesize insights, and present recommendations to cross-functional teams. Experience with usability testing, surveys, and analytics tools required. Healthcare industry experience is a plus.',
		'meta'       => array(
			'address'          => array(
				'address'     => '250 Hudson Street, Hudson Square, NY 10013',
				'lat'         => 40.7258,
				'lng'         => -74.0075,
				'city'        => 'New York',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '10013',
			),
			'company'          => 'HealthBridge Digital',
			'salary_min'       => 110000,
			'salary_max'       => 145000,
			'salary_type'      => 'annual',
			'experience_level' => 'mid',
			'remote_option'    => 'hybrid',
			'employment_type'  => 'full-time',
			'skills'           => array( 'User Research', 'Usability Testing', 'Survey Design', 'Data Analysis', 'Stakeholder Presentation' ),
			'apply_url'        => 'https://healthbridge.digital/careers/ux-researcher',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+25 days' ) ),
		),
	),
	array(
		'title'      => 'Visual Designer (Contract)',
		'type'       => 'job',
		'categories' => array( 'Design' ),
		'features'   => array( 'remote', 'learning' ),
		'tags'       => array( 'branding', 'illustration', 'motion', 'creative' ),
		'content'    => 'We need a talented visual designer for a 6-month contract to refresh our brand identity across web, mobile, and marketing materials. You will create illustrations, motion graphics, and marketing assets. Strong portfolio showcasing brand work is essential. This is a fully remote contract position.',
		'meta'       => array(
			'address'          => array(
				'address'     => '20 Jay Street, DUMBO, Brooklyn, NY 11201',
				'lat'         => 40.7033,
				'lng'         => -73.9866,
				'city'        => 'Brooklyn',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '11201',
			),
			'company'          => 'BrandCraft Studio',
			'salary_min'       => 65,
			'salary_max'       => 90,
			'salary_type'      => 'hourly',
			'experience_level' => 'mid',
			'remote_option'    => 'remote',
			'employment_type'  => 'contract',
			'skills'           => array( 'Adobe Creative Suite', 'Figma', 'Illustration', 'Motion Design', 'Branding' ),
			'apply_url'        => 'https://brandcraft.studio/work-with-us',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+14 days' ) ),
		),
	),
	array(
		'title'      => 'Design System Lead',
		'type'       => 'job',
		'categories' => array( 'Design' ),
		'features'   => array( 'hybrid', 'health-ins', '401k', 'equity', 'pto' ),
		'tags'       => array( 'design systems', 'components', 'tokens', 'documentation' ),
		'content'    => 'Build and maintain our design system used across 12 product teams. You will define design tokens, create component specifications, write documentation, and work closely with front-end engineers to ensure pixel-perfect implementation. This role bridges design and engineering.',
		'meta'       => array(
			'address'          => array(
				'address'     => '375 Park Avenue, Midtown, NY 10152',
				'lat'         => 40.7610,
				'lng'         => -73.9720,
				'city'        => 'New York',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '10152',
			),
			'company'          => 'FinServe Global',
			'salary_min'       => 155000,
			'salary_max'       => 195000,
			'salary_type'      => 'annual',
			'experience_level' => 'senior',
			'remote_option'    => 'hybrid',
			'employment_type'  => 'full-time',
			'skills'           => array( 'Design Systems', 'Figma', 'Component Libraries', 'Design Tokens', 'Front-end CSS' ),
			'apply_url'        => 'https://finserve.com/careers/design-system-lead',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+40 days' ) ),
		),
	),
	// ── Marketing ──
	array(
		'title'      => 'Content Marketing Manager',
		'type'       => 'job',
		'categories' => array( 'Marketing' ),
		'features'   => array( 'remote', 'health-ins', '401k', 'pto' ),
		'tags'       => array( 'content strategy', 'seo', 'blog', 'copywriting' ),
		'content'    => 'Own our content strategy from ideation to distribution. You will plan and execute a content calendar, write and edit blog posts, manage SEO strategy, and collaborate with the design team on visual content. Experience in B2B SaaS content marketing required. Must be a strong writer with an eye for data-driven optimization.',
		'meta'       => array(
			'address'          => array(
				'address'     => '30 Rockefeller Plaza, Midtown, NY 10112',
				'lat'         => 40.7587,
				'lng'         => -73.9787,
				'city'        => 'New York',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '10112',
			),
			'company'          => 'SaaSify',
			'salary_min'       => 95000,
			'salary_max'       => 125000,
			'salary_type'      => 'annual',
			'experience_level' => 'mid',
			'remote_option'    => 'remote',
			'employment_type'  => 'full-time',
			'skills'           => array( 'Content Strategy', 'SEO', 'Copywriting', 'Analytics', 'Project Management' ),
			'apply_url'        => 'https://saasify.io/careers/content-marketing',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+20 days' ) ),
		),
	),
	array(
		'title'      => 'Growth Marketing Analyst',
		'type'       => 'job',
		'categories' => array( 'Marketing' ),
		'features'   => array( 'hybrid', 'health-ins', '401k', 'learning' ),
		'tags'       => array( 'analytics', 'sql', 'a/b testing', 'growth' ),
		'content'    => 'Use data to unlock growth. Analyze marketing performance across channels, design and run A/B tests, build dashboards, and identify opportunities to improve conversion rates. Strong SQL skills and experience with analytics tools required. This role sits at the intersection of marketing and data science.',
		'meta'       => array(
			'address'          => array(
				'address'     => '4 Times Square, Midtown, NY 10036',
				'lat'         => 40.7565,
				'lng'         => -73.9862,
				'city'        => 'New York',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '10036',
			),
			'company'          => 'GrowthEngine',
			'salary_min'       => 85000,
			'salary_max'       => 115000,
			'salary_type'      => 'annual',
			'experience_level' => 'mid',
			'remote_option'    => 'hybrid',
			'employment_type'  => 'full-time',
			'skills'           => array( 'SQL', 'Google Analytics', 'A/B Testing', 'Data Visualization', 'Excel' ),
			'apply_url'        => 'https://growthengine.co/jobs/analyst',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+18 days' ) ),
		),
	),
	array(
		'title'      => 'Social Media Coordinator',
		'type'       => 'job',
		'categories' => array( 'Marketing' ),
		'features'   => array( 'onsite', 'health-ins', 'gym' ),
		'tags'       => array( 'social media', 'instagram', 'tiktok', 'community' ),
		'content'    => 'Manage our social presence across Instagram, TikTok, LinkedIn, and X. Create engaging content, respond to community interactions, and grow our following. You will plan campaigns, coordinate with influencers, and report on social metrics. This is an on-site role at our vibrant Chelsea office.',
		'meta'       => array(
			'address'          => array(
				'address'     => '601 West 26th Street, Chelsea, NY 10001',
				'lat'         => 40.7510,
				'lng'         => -74.0040,
				'city'        => 'New York',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '10001',
			),
			'company'          => 'Vibe Media Group',
			'salary_min'       => 55000,
			'salary_max'       => 70000,
			'salary_type'      => 'annual',
			'experience_level' => 'entry',
			'remote_option'    => 'onsite',
			'employment_type'  => 'full-time',
			'skills'           => array( 'Social Media Management', 'Content Creation', 'Canva', 'Video Editing', 'Community Management' ),
			'apply_url'        => 'https://vibemedia.com/careers/social',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+15 days' ) ),
		),
	),
	array(
		'title'      => 'Email Marketing Specialist',
		'type'       => 'job',
		'categories' => array( 'Marketing' ),
		'features'   => array( 'remote', 'health-ins', '401k' ),
		'tags'       => array( 'email', 'automation', 'segmentation', 'mailchimp' ),
		'content'    => 'Design and optimize email campaigns that drive engagement and revenue. You will build automated workflows, segment audiences, write compelling copy, and analyze campaign performance. Experience with marketing automation platforms required. E-commerce background is a plus.',
		'meta'       => array(
			'address'          => array(
				'address'     => '114 5th Avenue, Flatiron, NY 10011',
				'lat'         => 40.7380,
				'lng'         => -73.9912,
				'city'        => 'New York',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '10011',
			),
			'company'          => 'ShopWave Commerce',
			'salary_min'       => 70000,
			'salary_max'       => 90000,
			'salary_type'      => 'annual',
			'experience_level' => 'mid',
			'remote_option'    => 'remote',
			'employment_type'  => 'full-time',
			'skills'           => array( 'Email Marketing', 'Marketing Automation', 'Copywriting', 'Segmentation', 'A/B Testing' ),
			'apply_url'        => 'https://shopwave.com/careers/email-specialist',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+22 days' ) ),
		),
	),
	// ── Sales ──
	array(
		'title'      => 'Account Executive (Enterprise)',
		'type'       => 'job',
		'categories' => array( 'Sales' ),
		'featured'   => true,
		'features'   => array( 'hybrid', 'health-ins', '401k', 'equity' ),
		'tags'       => array( 'enterprise sales', 'b2b', 'saas', 'quota' ),
		'content'    => 'Close six- and seven-figure deals with Fortune 500 companies. You will manage the full sales cycle from prospecting to close, build relationships with C-level executives, and collaborate with solutions engineers on custom proposals. Base plus uncapped commission. Top earners make $300K+.',
		'meta'       => array(
			'address'          => array(
				'address'     => '340 Madison Avenue, Midtown, NY 10173',
				'lat'         => 40.7558,
				'lng'         => -73.9785,
				'city'        => 'New York',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '10173',
			),
			'company'          => 'DataVault Enterprise',
			'salary_min'       => 120000,
			'salary_max'       => 300000,
			'salary_type'      => 'annual',
			'experience_level' => 'senior',
			'remote_option'    => 'hybrid',
			'employment_type'  => 'full-time',
			'skills'           => array( 'Enterprise Sales', 'Salesforce', 'Negotiation', 'Presentation', 'Account Management' ),
			'apply_url'        => 'https://datavault.com/careers/ae-enterprise',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+30 days' ) ),
		),
	),
	array(
		'title'      => 'Sales Development Representative',
		'type'       => 'job',
		'categories' => array( 'Sales' ),
		'features'   => array( 'onsite', 'health-ins', 'learning', 'gym' ),
		'tags'       => array( 'sdr', 'outbound', 'prospecting', 'entry level' ),
		'content'    => 'Launch your sales career at one of NYC\'s fastest-growing startups. You will prospect target accounts, qualify leads, and book meetings for Account Executives. We provide world-class sales training and a clear promotion path to AE within 12 to 18 months. On-target earnings of $80K in year one.',
		'meta'       => array(
			'address'          => array(
				'address'     => '315 West 36th Street, Hudson Yards, NY 10018',
				'lat'         => 40.7545,
				'lng'         => -73.9940,
				'city'        => 'New York',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '10018',
			),
			'company'          => 'Launchpad AI',
			'salary_min'       => 50000,
			'salary_max'       => 80000,
			'salary_type'      => 'annual',
			'experience_level' => 'entry',
			'remote_option'    => 'onsite',
			'employment_type'  => 'full-time',
			'skills'           => array( 'Cold Calling', 'Email Outreach', 'CRM', 'Prospecting', 'Communication' ),
			'apply_url'        => 'https://launchpadai.com/careers/sdr',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+21 days' ) ),
		),
	),
	array(
		'title'      => 'Customer Success Manager',
		'type'       => 'job',
		'categories' => array( 'Sales' ),
		'features'   => array( 'remote', 'health-ins', '401k', 'pto' ),
		'tags'       => array( 'customer success', 'retention', 'onboarding', 'upsell' ),
		'content'    => 'Own the post-sale experience for our mid-market customers. You will drive product adoption, manage renewals, identify expansion opportunities, and serve as the voice of the customer internally. You will manage a portfolio of 40+ accounts and be measured on net revenue retention.',
		'meta'       => array(
			'address'          => array(
				'address'     => '100 Avenue of the Americas, SoHo, NY 10013',
				'lat'         => 40.7235,
				'lng'         => -74.0050,
				'city'        => 'New York',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '10013',
			),
			'company'          => 'InsightPlatform',
			'salary_min'       => 90000,
			'salary_max'       => 120000,
			'salary_type'      => 'annual',
			'experience_level' => 'mid',
			'remote_option'    => 'remote',
			'employment_type'  => 'full-time',
			'skills'           => array( 'Customer Success', 'Account Management', 'Product Training', 'Data Analysis', 'Communication' ),
			'apply_url'        => 'https://insightplatform.io/careers/csm',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+25 days' ) ),
		),
	),
	array(
		'title'      => 'Solutions Engineer (Pre-Sales)',
		'type'       => 'job',
		'categories' => array( 'Sales' ),
		'features'   => array( 'hybrid', 'health-ins', '401k', 'equity', 'learning' ),
		'tags'       => array( 'solutions engineering', 'technical sales', 'demos', 'api' ),
		'content'    => 'Bridge the gap between technical complexity and business value. You will partner with Account Executives to run technical demos, build proof-of-concept integrations, and answer detailed technical questions from prospects. Strong engineering background combined with customer-facing skills required.',
		'meta'       => array(
			'address'          => array(
				'address'     => '555 West 18th Street, Chelsea, NY 10011',
				'lat'         => 40.7435,
				'lng'         => -74.0068,
				'city'        => 'New York',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '10011',
			),
			'company'          => 'APIConnect Pro',
			'salary_min'       => 125000,
			'salary_max'       => 165000,
			'salary_type'      => 'annual',
			'experience_level' => 'mid',
			'remote_option'    => 'hybrid',
			'employment_type'  => 'full-time',
			'skills'           => array( 'API Integration', 'Technical Demos', 'Python', 'SQL', 'Presentation Skills' ),
			'apply_url'        => 'https://apiconnect.pro/careers/se',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+35 days' ) ),
		),
	),
	// ── Operations ──
	array(
		'title'      => 'People Operations Manager',
		'type'       => 'job',
		'categories' => array( 'Operations' ),
		'features'   => array( 'hybrid', 'health-ins', '401k', 'parental-leave', 'pto' ),
		'tags'       => array( 'hr', 'people ops', 'culture', 'onboarding' ),
		'content'    => 'Build and scale our people operations as we grow from 50 to 200 employees. You will own the full employee lifecycle from recruiting to offboarding, manage benefits administration, drive culture initiatives, and ensure compliance. This is a strategic role reporting directly to the COO.',
		'meta'       => array(
			'address'          => array(
				'address'     => '10 Hudson Yards, NY 10001',
				'lat'         => 40.7537,
				'lng'         => -74.0020,
				'city'        => 'New York',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '10001',
			),
			'company'          => 'NexGen Robotics',
			'salary_min'       => 100000,
			'salary_max'       => 135000,
			'salary_type'      => 'annual',
			'experience_level' => 'mid',
			'remote_option'    => 'hybrid',
			'employment_type'  => 'full-time',
			'skills'           => array( 'HR Management', 'Benefits Administration', 'Recruiting', 'Employee Relations', 'Compliance' ),
			'apply_url'        => 'https://nexgenrobotics.ai/careers/people-ops',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+30 days' ) ),
		),
	),
	array(
		'title'      => 'Project Manager (Agile)',
		'type'       => 'job',
		'categories' => array( 'Operations' ),
		'features'   => array( 'remote', 'health-ins', '401k', 'pto' ),
		'tags'       => array( 'agile', 'scrum', 'jira', 'project management' ),
		'content'    => 'Lead cross-functional teams through complex product launches. You will facilitate agile ceremonies, remove blockers, manage timelines, and keep stakeholders informed. PMP or CSM certification preferred. Experience managing engineering and design teams in a fast-paced environment is essential.',
		'meta'       => array(
			'address'          => array(
				'address'     => '195 Broadway, Financial District, NY 10007',
				'lat'         => 40.7108,
				'lng'         => -74.0093,
				'city'        => 'New York',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '10007',
			),
			'company'          => 'BuildFlow',
			'salary_min'       => 105000,
			'salary_max'       => 140000,
			'salary_type'      => 'annual',
			'experience_level' => 'mid',
			'remote_option'    => 'remote',
			'employment_type'  => 'full-time',
			'skills'           => array( 'Agile', 'Scrum', 'Jira', 'Stakeholder Management', 'Risk Assessment' ),
			'apply_url'        => 'https://buildflow.io/careers/pm',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+28 days' ) ),
		),
	),
	array(
		'title'      => 'Finance & Operations Analyst',
		'type'       => 'job',
		'categories' => array( 'Operations' ),
		'features'   => array( 'onsite', 'health-ins', '401k', 'learning' ),
		'tags'       => array( 'finance', 'budgeting', 'forecasting', 'excel' ),
		'content'    => 'Support strategic decision-making with financial modeling, budgeting, and operational analysis. You will build forecasts, track KPIs, prepare board materials, and identify cost optimization opportunities. Strong Excel and SQL skills required. CPA or MBA is a plus but not required.',
		'meta'       => array(
			'address'          => array(
				'address'     => '225 Liberty Street, Brookfield Place, NY 10281',
				'lat'         => 40.7133,
				'lng'         => -74.0150,
				'city'        => 'New York',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '10281',
			),
			'company'          => 'CapitalFlow Ventures',
			'salary_min'       => 80000,
			'salary_max'       => 110000,
			'salary_type'      => 'annual',
			'experience_level' => 'mid',
			'remote_option'    => 'onsite',
			'employment_type'  => 'full-time',
			'skills'           => array( 'Financial Modeling', 'Excel', 'SQL', 'Budgeting', 'Data Analysis' ),
			'apply_url'        => 'https://capitalflow.vc/careers/analyst',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+20 days' ) ),
		),
	),
	array(
		'title'      => 'Executive Assistant to CEO',
		'type'       => 'job',
		'categories' => array( 'Operations' ),
		'features'   => array( 'onsite', 'health-ins', '401k', 'gym' ),
		'tags'       => array( 'executive assistant', 'c-suite', 'scheduling', 'travel' ),
		'content'    => 'Provide high-level administrative support to the CEO of a Series C startup. You will manage a complex calendar, coordinate travel, prepare meeting materials, and handle confidential correspondence. This role requires exceptional organizational skills, discretion, and the ability to anticipate needs before they arise.',
		'meta'       => array(
			'address'          => array(
				'address'     => '888 Broadway, Union Square, NY 10003',
				'lat'         => 40.7370,
				'lng'         => -73.9905,
				'city'        => 'New York',
				'state'       => 'NY',
				'country'     => 'US',
				'postal_code' => '10003',
			),
			'company'          => 'FutureScale Technologies',
			'salary_min'       => 75000,
			'salary_max'       => 100000,
			'salary_type'      => 'annual',
			'experience_level' => 'mid',
			'remote_option'    => 'onsite',
			'employment_type'  => 'full-time',
			'skills'           => array( 'Calendar Management', 'Travel Coordination', 'Communication', 'Google Workspace', 'Discretion' ),
			'apply_url'        => 'https://futurescale.tech/careers/ea',
			'deadline'         => gmdate( 'Y-m-d', strtotime( '+14 days' ) ),
		),
	),
);

// ── Seed all listings ──

foreach ( $listings as $listing_data ) {
	$reviews = $listing_data['reviews'] ?? array();
	unset( $listing_data['reviews'] );

	Demo_Seeder::seed_listing( $listing_data );
}
